title: jbp.io
author:
  name: Joseph Birr-Pixton
  email: jbp@jbp.io
  github: ctz
  twitter: jpixton

production_url: https://jbp.io

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
kramdown:
  toc_levels: 1..2

